# Generated by Django 3.2.14 on 2022-07-30 10:29

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20220726_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[50, 80], upload_to='posts'),
        ),
    ]
